### ISSUE TITLE
Create InfoView

### ISSUE THREAD

**Issue by yoohyebin** [DeveloperAcademy-POSTECH/MC2-Team17-for.JOY#11]
## ✏️ Summary
사진, 음성에 대한 정보를 입력하는 View 구현

## ✨ Description
- 사진에 대한 제목 (최대 20자)
- 태그
    - 태그 입력 View modal로 구현
    - 태그 입력은 최대 10자, 최대 10개까지만 입력 가능
    - 초기에 3개의 기본 태그 제공
- 날짜
    - DatePicker 사용   

## ✓ Todo
- [x] 제목 입력 TextField구현
- [x] 태그 입력 View 구현
- [x] userdefault를 사용해 초기 태그 제공
- [x] DatePicker 구현
