### ISSUE TITLE
[Feat] Update GalleryView

### ISSUE THREAD

**Issue by NewYorkKim** [DeveloperAcademy-POSTECH/MC2-Team17-for.JOY#13]
## ✏️ Summary
특정 연도와 태그에 해당되는 추억을 모아볼 수 있는 GalleryView 구현

## ✨ Description
- 특정 연도와 태그에 해당하는 데이터 그리드 형태로 시각화
- 데이터를 시간순으로 정렬 가능

## ✓ Todo
- [x] 태그 + 연도 표시
- [x] 데이터 그리드 형태로 시각화
- [x] 데이터 시간순으로 정렬
- [x] 데이터 선택하면 CarouselView로 전환
- [x] backButton 선택하면 AlbumView로 전환
