### ISSUE TITLE
[Feat] Update CarouselView

### ISSUE THREAD

**Issue by NewYorkKim** [DeveloperAcademy-POSTECH/MC2-Team17-for.JOY#15]
## ✏️ Summary
추억을 자세히 살펴볼 수 있는 CarouselView 구현

## ✨ Description
- 스와이프하면 이전/이후 데이터로 이동 가능
- 데이터 정보 확인/편집/삭제 가능

## ✓ Todo
- [x] 무한 캐로셀 뷰 구현
- [x] 데이터 편집/삭제 버튼 추가
- [x] backButton 선택하면 GalleryView로 전환

## 🗒️ Note (optional)
DataManager 생성 이후, 음성 듣기 기능 추가 예정
