### ISSUE TITLE
[Design] Change Image Size

### ISSUE THREAD

**Issue by NewYorkKim** [DeveloperAcademy-POSTECH/MC2-Team17-for.JOY#53]
## ✏️ Summary
이미지 사이즈 수정

## ✨ Description
- ViewExtension 프레임 사이즈 수정
- ImageCropView 이미지 프레임 사이즈 수정
- CarouselView 이미지 프레임 사이즈 수정

## ✓ Todo
- [x] ViewExtension 프레임 사이즈 수정
- [x] ImageCropView 이미지 프레임 사이즈 수정
- [x] CarouselView 이미지 프레임 사이즈 수정
