### ISSUE TITLE
[Feat] Update AlbumView

### ISSUE THREAD

**Issue by NewYorkKim** [DeveloperAcademy-POSTECH/MC2-Team17-for.JOY#9]
## ✏️ Summary
연도별 추억 썸네일을 확인할 수 있는 AlbumView 구현

## ✨ Description
- 데이터베이스에 저장된 사진들이 연도별로 카테고리화
- 연도와 가장 최신 사진을 썸네일 형태로 확인 가능
- Tag를 활용하여 데이터 필터링 가능
- 날짜를 기준으로 정렬 가능

## ✓ Todo
- [x] ScrollView 안에 연도별 카테고리 시각화
- [x] 연도를 선택하면 GalleryView()로 전환
- [x] Tag 필터링 구현
- [x] 날짜 정렬 구현
